export const actionTypes = {
  ADD_POST: 'ADD-POST',
  UPD_NEW_POST_TXT: 'UPD-NEW-POST-TXT',
  ADD_MESSAGE: 'ADD-MESSAGE',
  UPD_NEW_MSG_TEXT: 'UPD-NEW-MSG-TXT',
  FOLLOW: 'FOLLOW',
  UN_FOLLOW: 'UN_FOLLOW',
  SET_USERS: 'SET_USERS',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_TOTAL_USERS_COUNT: 'SET_TOTAL_USERS_COUNT',
};