export const actionTypes = {
  ADD_POST: 'ADD-POST',
  UPD_NEW_POST_TXT: 'UPD-NEW-POST-TXT',
  ADD_MESSAGE: 'ADD-MESSAGE',
  UPD_NEW_MSG_TEXT: 'UPD-NEW-MSG-TXT',
  FOLLOW: 'FOLLOW',
  UN_FOLLOW: 'UN_FOLLOW',
  SET_USERS: 'SET_USERS',
  SET_TOTAL_USERS_COUNT: 'SET_TOTAL_USERS_COUNT',
  INCREASE_CURRENT_PAGE: 'INCREASE_CURRENT_PAGE',
  DECREASE_CURRENT_PAGE: 'DECREASE_CURRENT_PAGE',
  TOGGLE_IS_FETCHING: 'TOGGLE_IS_FETCHING',
  SET_USER_PROFILE: 'SET_USER_PROFILE',
};